name: LobbySystem
version: '${project.version}'
main: me.refluxo.lobbysystem.LobbySystem
api-version: 1.13
load: STARTUP
depend: [ Library ]
author: Refluxo Development
commands:
  setlocation:
    description: Setzt eine Position